Write-Host "=================================" -ForegroundColor Cyan
Write-Host "Preparando proyecto para Railway" -ForegroundColor Cyan
Write-Host "=================================" -ForegroundColor Cyan

# Verificar si git está inicializado
if (-not (Test-Path ".git")) {
    Write-Host "`nInicializando repositorio Git..." -ForegroundColor Yellow
    git init
    Write-Host "OK - Repositorio inicializado" -ForegroundColor Green
} else {
    Write-Host "`nRepositorio Git ya existe" -ForegroundColor Green
}

# Crear .gitignore si no existe
if (-not (Test-Path ".gitignore")) {
    Write-Host "`nCreando .gitignore..." -ForegroundColor Yellow
    @"
## Ignore Visual Studio temporary files, build results, and
## files generated by popular Visual Studio add-ons.

# User-specific files
*.suo
*.user
*.userosscache
*.sln.docstates

# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
build/
bld/
[Bb]in/
[Oo]bj/

# Visual Studio cache/options directory
.vs/

# MSTest test Results
[Tt]est[Rr]esult*/
[Bb]uild[Ll]og.*

# NuGet Packages
*.nupkg
**/packages/*

# Others
*.log
*.cache
appsettings.Development.json
"@ | Out-File -FilePath ".gitignore" -Encoding UTF8
    Write-Host "OK - .gitignore creado" -ForegroundColor Green
} else {
    Write-Host "`n.gitignore ya existe" -ForegroundColor Green
}

Write-Host "`n=================================" -ForegroundColor Cyan
Write-Host "Verificando archivos de Railway:" -ForegroundColor Cyan
Write-Host "=================================" -ForegroundColor Cyan

$files = @(
    "src/Services/Auth.Service/Dockerfile",
    "src/Services/Messages.Service/Dockerfile",
    "src/Services/Groups.Service/Dockerfile",
    "src/UI/Dockerfile",
    "railway.json",
    ".dockerignore",
    "RAILWAY_DEPLOYMENT.md"
)

foreach ($file in $files) {
    if (Test-Path $file) {
        Write-Host "✓ $file" -ForegroundColor Green
    } else {
        Write-Host "✗ $file (FALTA)" -ForegroundColor Red
    }
}

Write-Host "`n=================================" -ForegroundColor Yellow
Write-Host "SIGUIENTES PASOS:" -ForegroundColor Yellow
Write-Host "=================================" -ForegroundColor Yellow
Write-Host "1. Lee RAILWAY_DEPLOYMENT.md para instrucciones detalladas" -ForegroundColor White
Write-Host "`n2. Crea un repositorio en GitHub" -ForegroundColor White
Write-Host "`n3. Sube tu código:" -ForegroundColor White
Write-Host "   git add ." -ForegroundColor Cyan
Write-Host "   git commit -m 'Initial commit - Sistema de Mensajería'" -ForegroundColor Cyan
Write-Host "   git remote add origin https://github.com/TU_USUARIO/TPI-NET.git" -ForegroundColor Cyan
Write-Host "   git branch -M main" -ForegroundColor Cyan
Write-Host "   git push -u origin main" -ForegroundColor Cyan
Write-Host "`n4. Ve a Railway.app y sigue la guía en RAILWAY_DEPLOYMENT.md" -ForegroundColor White

Write-Host "`n¡Éxito! Tu proyecto está listo para Railway 🚀" -ForegroundColor Green
